apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bird-image-api
spec:
  selector:
    app: bird-image-api
  ports:
    - protocol: TCP
      port: {{ .Values.birdImageApi.port }}
      targetPort: {{ .Values.birdImageApi.port }}