apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bird-api
spec:
  selector:
    app: bird-api
  ports:
    - protocol: TCP
      port: {{ .Values.birdApi.port }}
      targetPort: {{ .Values.birdApi.port }}