name: docker-build-push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Bird API
      uses: docker/build-push-action@v2
      with:
        context: ../../bird
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bird-api:${{ github.sha }},
              ${{ secrets.DOCKERHUB_USERNAME }}/bird-api:latest

    - name: Build and push Bird Image API
      uses: docker/build-push-action@v2
      with:
        context: ../../birdImage
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bird-image-api:${{ github.sha }},
              ${{ secrets.DOCKERHUB_USERNAME }}/bird-image-api:latest
